# Site Specific Configuration
title: ASMap
description: The website for the ASMap project's research, development, and other resources.
url: https://asmap.dev
author: ASMap Website Authors

# Keywords
keywords: ['seo', 'key', 'words']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

